### ISSUE TITLE
KeyError: 'pic_video'

### ISSUE THREAD

**Issue by ladeca-d** [HeZhang1994/weibo-crawler#11]
Error message:
Traceback (most recent call last):
  File "H:/prbkp/weibo-crawler/run_WeiboCrawler.py", line 245, in <module>
    photo_str = card['mblog']['pic_video']
KeyError: 'pic_video'

I do not know why it appeared. I just use:
                    if card_info:
                        if 'pic_video' in card_info:
                            try:
                                photo_str = card['mblog']['pic_video']
                                photo_list = re.split('[,]', photo_str)
                                for photo in photo_list:
                                    # E.g., 'photo' = '0:000voDMsjx07t57qM583010f0100alDF0k01'.
                                    photo_code = re.split('[:]', photo)[1]
                                    photo_url = photo_url_start + photo_code + photo_url_end
                                    photo_urls.append(photo_url)
                            except:
                                pass

to skip the part of code to prevent sudden interruption.

Hope it can help for further improvement.

**Comment by HeZhang1994** [comment]
Hi eweca1992,

Thank you very much for presenting this issue! Could you please replace `photo_str = card['mblog']['pic_video']` with `photo_str = card_info['pic_video']`? I think the error occurs when the crawler trying to crawl live photos in retweeted Weibo posts. I will update the code shortly.

Best regards,
He
