### ISSUE TITLE
抓取到live photo会报错

### ISSUE THREAD

**Issue by Pangweiyun** [HeZhang1994/weibo-crawler#12]
换了不同人的账号，一到live photo就会报错
FileNotFoundError: [WinError 2] 系统找不到指定的文件
谢谢

**Comment by Pangweiyun** [comment]
改成IF_LIVE2GIF = False就好了
# True - Convert live photos to GIF images.
# False - Not convert live photos to GIF images.
意思是convert live photos to GIF images出了问题？

**Comment by HeZhang1994** [comment]
> 改成IF_LIVE2GIF = False就好了
> 
> # True - Convert live photos to GIF images.
> # False - Not convert live photos to GIF images.
> 意思是convert live photos to GIF images出了问题？

Hi Pangweiyun,

如果设置IF_LIVE2GIF = False不报错说明是live photo（实际是.mov格式的视频）转GIF出错。

结合你第一条的错误FileNotFoundError，我猜测是不是爬取的live photo（对应的.mov格式的视频）保存的路径有问题？如过你不是在Linux系统下运行程序，可以检查一下设置的Path格式，比如/和\等。:-)

Regards,
He
